### ISSUE TITLE
As a practitioner I want to visualize 3D geometry so I can better analyse the outputs of the simulation

### ISSUE THREAD

**Issue by jimenofonseca** [architecture-building-systems/cea-dashboard#4]
I believe our 2D mapping should be expanded to the use of Unity or related game engine, that help us to Visualize and interact with 3D geometry quickly.

The guys at FCL did something quite cool in this direction. I think we could think on implementing something similar.

**Comment by jimenofonseca** [comment]
@daren-thomas check this out (an example of the Unity 3D work): https://we.tl/lDMKOn3hiK

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can you put this on the timeline / roadmap? this could be really cool to do. i think i'd have to learn some stuff - like computer graphics, but it's something i've wanted to learn for quite some time and i'd be really excited to do this after the dashboard.
